export const ALGERIAN_CITIES = [
  "Adrar",
  "Aïn Defla",
  "Aïn Témouchent",
  "Alger",
  "Annaba",
  "Batna",
  "Béchar",
  "Béjaïa",
  "Béni Abbès",
  "Biskra",
  "Blida",
  "Bordj Badji Mokhtar",
  "Bordj Bou Arréridj",
  "Bouira",
  "Boumerdès",
  "Chlef",
  "Constantine",
  "Djanet",
  "Djelfa",
  "El Bayadh",
  "El M'Ghair",
  "El Meniaa",
  "El Oued",
  "El Tarf",
  "Ghardaïa",
  "Guelma",
  "Illizi",
  "In Guezzam",
  "In Salah",
  "Jijel",
  "Khenchela",
  "Laghouat",
  "Mascara",
  "Médéa",
  "Mila",
  "Mostaganem",
  "M'Sila",
  "Naâma",
  "Oran",
  "Ouargla",
  "Ouled Djellal",
  "Oum El Bouaghi",
  "Relizane",
  "Saïda",
  "Sétif",
  "Sidi Bel Abbès",
  "Skikda",
  "Souk Ahras",
  "Tamanrasset",
  "Tébessa",
  "Tiaret",
  "Timimoun",
  "Tindouf",
  "Tipaza",
  "Tissemsilt",
  "Tizi Ouzou",
  "Tlemcen",
  "Touggourt",
];

export interface Listing {
  id: string;
  type: "shipment" | "trip";
  title: string;
  from: string;
  to: string;
  date: string;
  price: number;
  weight?: string;
  dimensions?: string;
  description: string;
  user: {
    name: string;
    rating: number;
    reviews: number;
    avatar: string;
  };
  image?: string;
  category?: string;
}

export const SAMPLE_LISTINGS: Listing[] = [
  {
    id: "1",
    type: "shipment",
    title: "Machine à laver Samsung 8kg",
    from: "Alger",
    to: "Oran",
    date: "2026-04-05",
    price: 3500,
    weight: "65 kg",
    dimensions: "60x60x85 cm",
    description: "Machine à laver en bon état, bien emballée. Besoin de livraison soignée.",
    category: "Électroménager",
    user: { name: "Karim B.", rating: 4.8, reviews: 23, avatar: "KB" },
  },
  {
    id: "2",
    type: "trip",
    title: "Trajet Alger → Constantine - Place disponible",
    from: "Alger",
    to: "Constantine",
    date: "2026-04-03",
    price: 1500,
    weight: "jusqu'à 30 kg",
    description: "Je fais le trajet samedi matin en fourgon. Place disponible pour colis moyens.",
    user: { name: "Youcef M.", rating: 4.9, reviews: 47, avatar: "YM" },
  },
  {
    id: "3",
    type: "shipment",
    title: "Canapé 3 places cuir",
    from: "Sétif",
    to: "Alger",
    date: "2026-04-07",
    price: 5000,
    weight: "45 kg",
    dimensions: "200x90x85 cm",
    description: "Canapé acheté sur Ouedkniss, vendeur à Sétif. Besoin de transport.",
    category: "Meubles",
    user: { name: "Amina T.", rating: 4.7, reviews: 12, avatar: "AT" },
  },
  {
    id: "4",
    type: "trip",
    title: "Trajet Oran → Tlemcen - Camionnette",
    from: "Oran",
    to: "Tlemcen",
    date: "2026-04-04",
    price: 2000,
    weight: "jusqu'à 100 kg",
    description: "Camionnette avec grand espace. Peut transporter meubles ou électroménager.",
    user: { name: "Mohamed A.", rating: 5.0, reviews: 89, avatar: "MA" },
  },
  {
    id: "5",
    type: "shipment",
    title: "Réfrigérateur LG No Frost",
    from: "Annaba",
    to: "Constantine",
    date: "2026-04-06",
    price: 4000,
    weight: "70 kg",
    dimensions: "70x65x180 cm",
    description: "Réfrigérateur neuf à livrer. Emballage d'origine.",
    category: "Électroménager",
    user: { name: "Sara K.", rating: 4.6, reviews: 8, avatar: "SK" },
  },
  {
    id: "6",
    type: "trip",
    title: "Alger → Béjaïa - Véhicule utilitaire",
    from: "Alger",
    to: "Béjaïa",
    date: "2026-04-05",
    price: 2500,
    weight: "jusqu'à 200 kg",
    description: "Grand véhicule utilitaire. Idéal pour déménagement partiel.",
    user: { name: "Rachid L.", rating: 4.9, reviews: 156, avatar: "RL" },
  },
  {
    id: "7",
    type: "shipment",
    title: "Colis de vêtements (3 cartons)",
    from: "Blida",
    to: "Batna",
    date: "2026-04-08",
    price: 1200,
    weight: "15 kg",
    dimensions: "3x 40x40x40 cm",
    description: "3 cartons de vêtements bien emballés. Pas fragile.",
    category: "Cartons",
    user: { name: "Leila H.", rating: 4.5, reviews: 5, avatar: "LH" },
  },
  {
    id: "8",
    type: "trip",
    title: "Constantine → Annaba - Fourgon",
    from: "Constantine",
    to: "Annaba",
    date: "2026-04-03",
    price: 1800,
    weight: "jusqu'à 150 kg",
    description: "Fourgon Mercedes Sprinter. Trajet régulier chaque semaine.",
    user: { name: "Fares D.", rating: 4.8, reviews: 203, avatar: "FD" },
  },
];

export const CATEGORIES = [
  "Tous",
  "Électroménager",
  "Meubles",
  "Cartons",
  "Électronique",
  "Véhicules",
  "Matériaux",
  "Autre",
];

export const EUROPEAN_COUNTRIES = [
  {
    name: "France",
    flag: "🇫🇷",
    code: "FR",
    cities: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Bordeaux", "Lille", "Strasbourg", "Nantes", "Montpellier", "Grenoble", "Rennes"],
  },
  {
    name: "Espagne",
    flag: "🇪🇸",
    code: "ES",
    cities: ["Madrid", "Barcelone", "Valence", "Séville", "Saragosse", "Málaga", "Bilbao", "Alicante", "Murcie", "Las Palmas"],
  },
  {
    name: "Belgique",
    flag: "🇧🇪",
    code: "BE",
    cities: ["Bruxelles", "Anvers", "Gand", "Liège", "Bruges", "Namur", "Louvain", "Mons"],
  },
  {
    name: "Allemagne",
    flag: "🇩🇪",
    code: "DE",
    cities: ["Berlin", "Munich", "Hambourg", "Francfort", "Cologne", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig"],
  },
  {
    name: "Italie",
    flag: "🇮🇹",
    code: "IT",
    cities: ["Rome", "Milan", "Naples", "Turin", "Palerme", "Gênes", "Bologne", "Florence", "Venise", "Catane"],
  },
];

export const INTERNATIONAL_LISTINGS: Listing[] = [
  // --- Shipment requests (senders) ---
  {
    id: "int-s1",
    type: "shipment",
    title: "Colis vêtements et affaires personnelles",
    from: "Paris",
    to: "Alger",
    date: "2026-04-20",
    price: 3000,
    weight: "12 kg",
    dimensions: "50x40x30 cm",
    description: "2 cartons de vêtements et affaires diverses. Bien emballés, pas fragile.",
    category: "Cartons",
    user: { name: "Rania M.", rating: 4.8, reviews: 6, avatar: "RM" },
  },
  {
    id: "int-s2",
    type: "shipment",
    title: "Colis électronique — Laptop + accessoires",
    from: "Bruxelles",
    to: "Oran",
    date: "2026-04-25",
    price: 4500,
    weight: "5 kg",
    dimensions: "40x30x15 cm",
    description: "Ordinateur portable neuf et ses accessoires. Fragile, manipulation soignée requise.",
    category: "Électronique",
    user: { name: "Tarek B.", rating: 5.0, reviews: 14, avatar: "TB" },
  },
  {
    id: "int-s3",
    type: "shipment",
    title: "Médicaments et produits de pharmacie",
    from: "Lyon",
    to: "Constantine",
    date: "2026-04-22",
    price: 2500,
    weight: "3 kg",
    description: "Médicaments pour la famille. Urgent. Documents douaniers fournis.",
    category: "Autre",
    user: { name: "Nadia K.", rating: 4.9, reviews: 3, avatar: "NK" },
  },
  {
    id: "int-s4",
    type: "shipment",
    title: "Cadeaux et affaires familiales",
    from: "Alger",
    to: "Madrid",
    date: "2026-05-01",
    price: 3800,
    weight: "8 kg",
    description: "Colis de cadeaux pour la famille en Espagne. Emballage soigné.",
    category: "Cartons",
    user: { name: "Yassine A.", rating: 4.7, reviews: 9, avatar: "YA" },
  },
  // --- Trip listings (transporters) ---
  {
    id: "int-1",
    type: "trip",
    title: "Trajet Paris → Alger - Fourgon",
    from: "Paris",
    to: "Alger",
    date: "2026-04-18",
    price: 4500,
    weight: "jusqu'à 80 kg",
    description: "Je fais le trajet Paris–Alger en fourgon. Place disponible pour colis de toutes tailles. Trajet régulier mensuel.",
    user: { name: "Nassim B.", rating: 4.9, reviews: 38, avatar: "NB" },
  },
  {
    id: "int-2",
    type: "trip",
    title: "Trajet Alger → Lyon - Camionnette",
    from: "Alger",
    to: "Lyon",
    date: "2026-04-22",
    price: 5000,
    weight: "jusqu'à 120 kg",
    description: "Camionnette avec grand espace de chargement. Idéal pour colis lourds ou volumineux. Documents douaniers pris en charge.",
    user: { name: "Kamel R.", rating: 5.0, reviews: 61, avatar: "KR" },
  },
  {
    id: "int-3",
    type: "trip",
    title: "Madrid → Oran - Place disponible",
    from: "Madrid",
    to: "Oran",
    date: "2026-04-20",
    price: 3800,
    weight: "jusqu'à 50 kg",
    description: "Trajet régulier Madrid–Oran. Transporteur vérifié, assurance incluse.",
    user: { name: "Walid A.", rating: 4.8, reviews: 24, avatar: "WA" },
  },
  {
    id: "int-4",
    type: "trip",
    title: "Bruxelles → Alger - Fourgon Mercedes",
    from: "Bruxelles",
    to: "Alger",
    date: "2026-04-25",
    price: 4200,
    weight: "jusqu'à 100 kg",
    description: "Fourgon Mercedes Sprinter. Trajet mensuel régulier Bruxelles–Alger. Expérience 5 ans.",
    user: { name: "Sofiane M.", rating: 4.9, reviews: 112, avatar: "SM" },
  },
  {
    id: "int-5",
    type: "trip",
    title: "Alger → Berlin - Camion",
    from: "Alger",
    to: "Berlin",
    date: "2026-05-02",
    price: 7000,
    weight: "jusqu'à 300 kg",
    description: "Grand camion disponible. Idéal pour déménagement partiel ou colis multiples.",
    user: { name: "Hichem T.", rating: 4.7, reviews: 55, avatar: "HT" },
  },
  {
    id: "int-6",
    type: "trip",
    title: "Milan → Constantine - Voiture",
    from: "Milan",
    to: "Constantine",
    date: "2026-04-28",
    price: 3500,
    weight: "jusqu'à 40 kg",
    description: "Je rentre à Constantine depuis Milan. Espace pour petits colis ou affaires personnelles.",
    user: { name: "Anis K.", rating: 4.6, reviews: 17, avatar: "AK" },
  },
];
